### ISSUE TITLE
Allow transient action versions to be specified

### ISSUE THREAD

**Issue by airtonix** [rossjrw/pr-preview-action#10]

**Comment by airtonix** [comment]
https://github.com/JamesIves/github-pages-deploy-action/issues/1103

**Comment by rossjrw** [comment]
I don't know what you mean by this - could you please add a more detailed description?

**Comment by rossjrw** [comment]
@airtonix I'm going to close this issue as it's not clear what you want. Feel free to reopen it with a more detailed description.

**Comment by airtonix** [comment]
@rossjrw needs to be reopened. 

i didnt get notified.

bascially you hard code the version of your transient actions. those versions are broken.

if you make the version an input we can specify a version we want without continually requiring you to update the repo

**Comment by airtonix** [comment]
it's a shame, really. i wanted to use this, but nothing worked so yeah... looks like I'll have to fork it and publish my own version with fixes
