### ISSUE TITLE
Use custom domain for preview

### ISSUE THREAD

**Issue by FarisZR** [rossjrw/pr-preview-action#12]
First, thanks for the Awesome Project!

I have a repo that uses a custom URL, but the actions still uses the normal GitHub Pages URL.
It would be great if there is a way to set a custom URL for the action to use, that would also help if someone is using this on another page host.

**Comment by MSevey** [comment]
Any update on this? My team also is using a custom domain and would like this feature so that the previews load.

**Comment by rossjrw** [comment]
@MSevey None yet, but thanks for the interest. I plan to get around to this eventually, but in the meantime I'd be happy to review a PR if you can find time to contribute.

**Comment by leog** [comment]
Bumped into this too. Awesome job on the action @rossjrw, super useful!
I think the best approach would be to detect if the repository has a CNAME file and use its content as `pagesurl`. 
Unfortunately I'm not into Ruby so it might take me a while to implement it.

**Comment by vincerubinetti** [comment]
Maybe you can use this directly or as a reference:
https://github.com/actions/configure-pages

It looks pretty involved just to get the baseurl :/

What if you allowed this action to take a `baseurl` parameter, then you could run the `actions/configure-pages` before it and use its "calculated" `baseurl` output.

Sidenote, I really think `umbrella-dir` should be called `preview-dir`.

**Comment by rossjrw** [comment]
Housekeeping: Looks like this was resolved in [v1.3.0](https://github.com/rossjrw/pr-preview-action/releases/tag/v1.3.0) (#24) with the addition of the `custom-url` parameter, so I'm closing this issue - please reopen if this isn't the case
