### ISSUE TITLE
Set preview URL as action output

### ISSUE THREAD

**Issue by EndBug** [rossjrw/pr-preview-action#16]
It would be nice to have the resulting preview URL as an action output, so that it can be used in different contexts.
In composite actions, this can be done [like this](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file)

**Comment by rossjrw** [comment]
Good idea. It'll be a while before I get a chance to work on this - you seem familiar with the docs, so if you feel comfortable with contributing I'd gladly accept a PR.
