### ISSUE TITLE
Please allow passing the token 

### ISSUE THREAD

**Issue by lumag** [rossjrw/pr-preview-action#41]
The `JamesIves/github-pages-deploy-action`  and `marocchino/sticky-pull-request-comment` actions allow using personal access token in addition to the `GITHUB_TOKEN`. Please allow users of your action to also specify the token to be passed to the called actions.

**Comment by MH4GF** [comment]
FYI: A feature that allows users to specify a token is included in the PR here: https://github.com/rossjrw/pr-preview-action/pull/38
