### ISSUE TITLE
Link to branch links to current repository and not `deploy-repository`

### ISSUE THREAD

**Issue by DusterTheFirst** [rossjrw/pr-preview-action#50]
When the action creates the comment on the PR, the link provided to the `preview-branch` does not point to the `deploy-repository` but the repository that the PR was made on.

![image](https://github.com/rossjrw/pr-preview-action/assets/14093962/a6bfebf3-6cb1-48f8-8084-321ed3cb5fdd)

**Comment by rossjrw** [comment]
Fixed in v1.4.5
