### ISSUE TITLE
Comment shows target repo version, not action version

### ISSUE THREAD

**Issue by gzaripov** [rossjrw/pr-preview-action#51]
We have a lot of different tags in our repo using it in documentation preview title is kind of silly. Please add feature to change or remove it, it would make our PR comment much nicer!

Example of how it looks right now:
<img width="635" alt="image" src="https://github.com/rossjrw/pr-preview-action/assets/15311091/b8b30746-8c24-4f84-b22a-f649801e24ef">

**Comment by rossjrw** [comment]
Oh no! That's not supposed to happen. That's supposed to show the current version of PR Preview Action, not the version of the repository being previewed. Sort of nuts that I missed this. Thanks for raising!

**Comment by gzaripov** [comment]
Here are logs with details
<img width="1466" alt="image" src="https://github.com/rossjrw/pr-preview-action/assets/15311091/7a6a749d-372a-46b3-b6b2-a2d90e8a74b8">

**Comment by gzaripov** [comment]
The same thing when I set the latest version of action explicitly
<img width="1061" alt="image" src="https://github.com/rossjrw/pr-preview-action/assets/15311091/383615c3-f5ff-4a3c-8881-4a91ade5851a">

**Comment by rossjrw** [comment]
Thanks @gzaripov. Fixed in v1.4.3

**Comment by gzaripov** [comment]
I confirm that fix works! Thank you so much for a quick fix!
