### ISSUE TITLE
Broken operation in Container (regression)

### ISSUE THREAD

**Issue by predominant** [rossjrw/pr-preview-action#55]
https://github.com/rossjrw/pr-preview-action/commit/aa0f798d7a8862266c793affdfd62ad96edd14d9

This commit breaks operation in a container (same as issue https://github.com/rossjrw/pr-preview-action/issues/43)

**Comment by rossjrw** [comment]
Thank you for the concise report and for very politely letting me know that I'm an idiot. Fixed in v1.4.4, any usage pinned to v1 will automatically update.

**Comment by predominant** [comment]
No problem! Thankyou so much for your quick fix! <3
